### ISSUE TITLE
可否给个运行步骤

### ISSUE THREAD

**Issue by hy-allron** [youngLake/clientone#1]
怎么启动怎么访问的

**Comment by youngLake** [comment]
@hy-allron 抱歉才看到，简单来说先把cas-server启动起来，然后再在clienone的application.yml配置cas-server的url，以及clientone自己的url，再启动clientone，然后访问ip:port/clientone/logon就会跳转到cas登录页面

**Comment by hy-allron** [comment]
为啥你的cas-server是maven骨架，现在官网的这个5.2.6却是gradle，你下的不是官网的吗

**Comment by youngLake** [comment]
@hy-allron 是下载的官网的，然后重新整合了一下，也基本属于无侵入式的改造，只是添加了自己的校验器

**Comment by hy-allron** [comment]
能给个联系方式吗，我从官网下的没有src目录就是看不到源代码所以改不了配置但是你的有

**Comment by youngLake** [comment]
你看不到源码可能是因为你下载的template-overlay 这个是cas5.2.6的源码下载地址，你看看 
  https://codeload.github.com/apereo/cas/tar.gz/v5.2.6

**Comment by hy-allron** [comment]
谢谢啦
